// <auto-generated />
using System;
using LosSantosGarage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LosSantosGarage.Api.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260930022249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.GarageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("GarageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleGameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.HasIndex("VehicleGameId");

                    b.ToTable("GarageItems");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.VehicleGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("VehicleId", "GameId")
                        .IsUnique();

                    b.ToTable("VehicleGames");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.GarageItem", b =>
                {
                    b.HasOne("LosSantosGarage.Api.Entities.Garage", "Garage")
                        .WithMany("GarageItems")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LosSantosGarage.Api.Entities.VehicleGame", "VehicleGame")
                        .WithMany("GarageItems")
                        .HasForeignKey("VehicleGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");

                    b.Navigation("VehicleGame");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.VehicleGame", b =>
                {
                    b.HasOne("LosSantosGarage.Api.Entities.Game", "Game")
                        .WithMany("VehicleGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LosSantosGarage.Api.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleGames")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Game", b =>
                {
                    b.Navigation("VehicleGames");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Garage", b =>
                {
                    b.Navigation("GarageItems");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleGames");
                });

            modelBuilder.Entity("LosSantosGarage.Api.Entities.VehicleGame", b =>
                {
                    b.Navigation("GarageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
